////
  The contents of this file are subject to the terms of the Common Development and
  Distribution License (the License). You may not use this file except in compliance with the
  License.
 
  You can obtain a copy of the License at legal/CDDLv1.0.txt. See the License for the
  specific language governing permission and limitations under the License.
 
  When distributing Covered Software, include this CDDL Header Notice in each file and include
  the License file at legal/CDDLv1.0.txt. If applicable, add the following below the CDDL
  Header, with the fields enclosed by brackets [] replaced by your own identifying
  information: "Portions copyright [year] [name of copyright owner]".
 
  Copyright 2017 ForgeRock AS.
  Portions Copyright 2024 3A Systems LLC.
////

= Directory Server Developer's Guide
:doctype: book
:toc:
:authors: Mark Craig
:copyright: Copyright 2015-2017 ForgeRock AS.
:copyright: Portions Copyright 2024 3A Systems LLC.

:imagesdir: ../
:figure-caption!:
:example-caption!:
:table-caption!:
[abstract]
Hands-on guide to using OpenDJ directory server with an emphasis on command-line tools. The OpenDJ project offers open source LDAP directory services in Java.

include::./preface.adoc[]
include::./chap-rest-operations.adoc[]
include::./chap-rest-operations-3-0.adoc[]
include::./chap-ldap-operations.adoc[]
include::./chap-schema.adoc[]
include::./chap-groups.adoc[]
include::./chap-virtual-attrs-collective-attrs.adoc[]
include::./chap-referrals.adoc[]
include::./chap-writing-plugins.adoc[]
