'\" t
.\"     Title: backup
.\"    Author: 
.\" Generator: DocBook XSL-NS Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 05/16/2013
.\"    Manual: Tools Reference
.\"    Source: OpenDJ 2.6.0
.\"  Language: English
.\"
.TH "BACKUP" "1" "05/16/2013" "OpenDJ 2\&.6\&.0" "Tools Reference"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
backup \- back up OpenDJ directory data
.SH "SYNOPSIS"
.HP \w'\fBbackup\fR\ 'u
\fBbackup\fR {options}
.SH "DESCRIPTION"
.PP
This utility can be used to back up one or more directory server backends\&.
.SH "OPTIONS"
.PP
The following options are supported\&.
.PP
\fB\-a, \-\-backUpAll\fR
.RS 4
Back up all backends in the server
.RE
.PP
\fB\-A, \-\-hash\fR
.RS 4
Generate a hash of the backup contents
.RE
.PP
\fB\-B, \-\-incrementalBaseID {backupID}\fR
.RS 4
Backup ID of the source archive for an incremental backup\&.
.RE
.PP
\fB\-c, \-\-compress\fR
.RS 4
Compress the backup content
.RE
.PP
\fB\-d, \-\-backupDirectory {backupDir}\fR
.RS 4
Path to the target directory for the backup file(s)
.RE
.PP
\fB\-i, \-\-incremental\fR
.RS 4
Perform an incremental backup rather than a full backup
.RE
.PP
\fB\-I, \-\-backupID {backupID}\fR
.RS 4
Use the provided identifier for the backup
.RE
.PP
\fB\-n, \-\-backendID {backendName}\fR
.RS 4
Backend ID for the backend to archive
.RE
.PP
\fB\-s, \-\-signHash\fR
.RS 4
Sign the hash of the backup contents
.RE
.PP
\fB\-y, \-\-encrypt\fR
.RS 4
Encrypt the backup contents
.RE
.SS "Task Backend Connection Options"
.PP
\fB\-\-connectTimeout {timeout}\fR
.RS 4
Maximum length of time (in milliseconds) that can be taken to establish a connection\&. Use \*(Aq0\*(Aq to specify no time out\&.
.sp
Default value: 30000
.RE
.PP
\fB\-D, \-\-bindDN {bindDN}\fR
.RS 4
DN to use to bind to the server
.sp
Default value: cn=Directory Manager
.RE
.PP
\fB\-h, \-\-hostname {host}\fR
.RS 4
Directory server hostname or IP address
.sp
Default value: localhost\&.localdomain
.RE
.PP
\fB\-j, \-\-bindPasswordFile {bindPasswordFile}\fR
.RS 4
Bind password file
.RE
.PP
\fB\-K, \-\-keyStorePath {keyStorePath}\fR
.RS 4
Certificate key store path
.RE
.PP
\fB\-N, \-\-certNickname {nickname}\fR
.RS 4
Nickname of certificate for SSL client authentication
.RE
.PP
\fB\-o, \-\-saslOption {name=value}\fR
.RS 4
SASL bind options
.RE
.PP
\fB\-p, \-\-port {port}\fR
.RS 4
Directory server administration port number
.sp
Default value: 4444
.RE
.PP
\fB\-P, \-\-trustStorePath {trustStorePath}\fR
.RS 4
Certificate trust store path
.RE
.PP
\fB\-T, \-\-trustStorePassword {trustStorePassword}\fR
.RS 4
Certificate trust store PIN
.RE
.PP
\fB\-u, \-\-keyStorePasswordFile {keyStorePasswordFile}\fR
.RS 4
Certificate key store PIN file
.RE
.PP
\fB\-U, \-\-trustStorePasswordFile {path}\fR
.RS 4
Certificate trust store PIN file
.RE
.PP
\fB\-w, \-\-bindPassword {bindPassword}\fR
.RS 4
Password to use to bind to the server
.sp
Use
\fB\-w \-\fR
to have the command prompt for the password, rather than enter the password on the command line\&.
.RE
.PP
\fB\-W, \-\-keyStorePassword {keyStorePassword}\fR
.RS 4
Certificate key store PIN
.RE
.PP
\fB\-X, \-\-trustAll\fR
.RS 4
Trust all server SSL certificates
.RE
.SS "Task Scheduling Options"
.PP
\fB\-\-completionNotify {emailAddress}\fR
.RS 4
Email address of a recipient to be notified when the task completes\&. This option may be specified more than once\&.
.RE
.PP
\fB\-\-dependency {taskID}\fR
.RS 4
ID of a task upon which this task depends\&. A task will not start execution until all its dependencies have completed execution\&.
.RE
.PP
\fB\-\-errorNotify {emailAddress}\fR
.RS 4
Email address of a recipient to be notified if an error occurs when this task executes\&. This option may be specified more than once\&.
.RE
.PP
\fB\-\-failedDependencyAction {action}\fR
.RS 4
Action this task will take should one if its dependent tasks fail\&. The value must be one of PROCESS, CANCEL, DISABLE\&. If not specified defaults to CANCEL\&.
.RE
.PP
\fB\-\-recurringTask {schedulePattern}\fR
.RS 4
Indicates the task is recurring and will be scheduled according to the value argument expressed in crontab(5) compatible time/date pattern\&.
.RE
.PP
\fB\-t, \-\-start {startTime}\fR
.RS 4
Indicates the date/time at which this operation will start when scheduled as a server task expressed in YYYYMMDDhhmmssZ format for UTC time or YYYYMMDDhhmmss for local time\&. A value of \*(Aq0\*(Aq will cause the task to be scheduled for immediate execution\&. When this option is specified the operation will be scheduled to start at the specified time after which this utility will exit immediately\&.
.RE
.SS "Utility Input/Output Options"
.PP
\fB\-\-noPropertiesFile\fR
.RS 4
No properties file will be used to get default command line argument values
.RE
.PP
\fB\-\-propertiesFilePath {propertiesFilePath}\fR
.RS 4
Path to the file containing default property values used for command line arguments
.RE
.SS "General Options"
.PP
\fB\-V, \-\-version\fR
.RS 4
Display version information
.RE
.PP
\fB\-?, \-H, \-\-help\fR
.RS 4
Display usage information
.RE
.SH "EXIT CODES"
.PP
0
.RS 4
The command completed successfully\&.
.RE
.PP
1
.RS 4
An error occurred while parsing the command\-line arguments\&.
.RE
.SH "EXAMPLES"
.PP
The following example backs up all user data while the server is online\&.
.sp
.if n \{\
.RS 4
.\}
.nf
$ backup \-p 4444 \-D "cn=Directory Manager" \-w password
 \-a \-d /path/to/opendj/bak \-t 0
Backup task 20110613143801866 scheduled to start Jun 13, 2011 2:38:01 PM CEST
.fi
.if n \{\
.RE
.\}
.PP
The following example schedules back up of all user data every night at 2 AM when the server is online, and notifies diradmin@example\&.com when finished, or on error\&.
.sp
.if n \{\
.RS 4
.\}
.nf
$ backup \-p 4444 \-D "cn=Directory Manager" \-w password \-a
 \-d /path/to/opendj/bak \-\-recurringTask "00 02 * * *"
 \-\-completionNotify diradmin@example\&.com \-\-errorNotify diradmin@example\&.com
Recurring Backup task BackupTask\-988d6adf\-4d65\-44bf\-8546\-6ea74a2480b0
scheduled successfully
.fi
.if n \{\
.RE
.\}
.PP
The following example backs up all user data while the server is offline\&.
.sp
.if n \{\
.RS 4
.\}
.nf
$ /path/to/opendj/bin/stop\-ds
Stopping Server\&.\&.\&.
\&.\&.\&.
$ /path/to/opendj/bin/backup \-\-backupAll \-\-backupDirectory /path/to/opendj/bak
\&.\&.\&.
[28/Sep/2012:12:14:22 +0200] \&.\&.\&. msg=The backup process completed successfully
$ /path/to/opendj/bin/start\-ds
[28/Sep/2012:12:15:48 +0200] \&.\&.\&. The Directory Server has started successfully
.fi
.if n \{\
.RE
.\}
.SH "COPYRIGHT"
.br
Copyright \(co 2011-2013 ForgeRock AS
.br
