'\" te
.\" Copyright (c) 2008, Sun Microsystems Inc. All
.\" Rights Reserved.
.TH control-panel 1 "December 2008" "1.1" "User Commands"
.SH NAME
control-panel \- launches a graphical user interface
that displays server status information and enables you to perform basic directory
server administration
.SH SYNOPSIS
.LP
.nf
\fBcontrol-panel\fR \fIoptions\fR
.fi

.SH DESCRIPTION
.sp
.LP
The \fBcontrol-panel\fR command launches a graphical user
interface that displays server status information and enables you to perform
basic directory server administration. The control panel enables you to perform
certain data management tasks such as managing entries, importing and exporting
data, and backing up and restoring data. The control panel also enables you
to manage directory schema and indexes, and to set server runtime options.
.SH OPTIONS
.sp
.LP
The following options are supported:
.sp
.ne 2
.mk
.na
\fB\fB-V\fR, \fB--version\fR\fR
.ad
.RS 18n
.rt  
Display Directory Server version information.
.RE

.sp
.ne 2
.mk
.na
\fB\fB-?\fR, \fB-H\fR, \fB--help\fR\fR
.ad
.RS 18n
.rt  
Displays usage information.
.RE

.SH ATTRIBUTES
.sp
.LP
See \fBattributes\fR(5) for
descriptions of the following attributes:
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
ATTRIBUTE TYPEATTRIBUTE VALUE
_
Interface StabilityUncommitted
.TE

