'\" t
.\"     Title: setup
.\"    Author: 
.\" Generator: DocBook XSL-NS Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 05/16/2013
.\"    Manual: Tools Reference
.\"    Source: OpenDJ 2.6.0
.\"  Language: English
.\"
.TH "SETUP" "1" "05/16/2013" "OpenDJ 2\&.6\&.0" "Tools Reference"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
setup \- install OpenDJ directory server
.SH "SYNOPSIS"
.HP \w'\fBsetup\fR\ 'u
\fBsetup\fR [options]
.SH "DESCRIPTION"
.PP
This utility can be used to setup the directory server\&.
.SH "OPTIONS"
.PP
The following options are supported\&.
.PP
\fB\-a, \-\-addBaseEntry\fR
.RS 4
Indicates whether to create the base entry in the directory server database
.RE
.PP
\fB\-\-adminConnectorPort {port}\fR
.RS 4
Port on which the Administration Connector should listen for communication
.sp
Default value: 4444
.RE
.PP
\fB\-b, \-\-baseDN {baseDN}\fR
.RS 4
Base DN for user information in the directory server\&. Multiple base DNs may be provided by using this option multiple times
.sp
Default value: dc=example,dc=com
.RE
.PP
\fB\-d, \-\-sampleData {numEntries}\fR
.RS 4
Specifies that the database should be populated with the specified number of sample entries
.sp
Default value: 0
.RE
.PP
\fB\-D, \-\-rootUserDN {rootUserDN}\fR
.RS 4
DN for the initial root user for the directory server
.sp
Default value: cn=Directory Manager
.RE
.PP
\fB\-\-generateSelfSignedCertificate\fR
.RS 4
Generate a self\-signed certificate that the server should use when accepting SSL\-based connections or performing StartTLS negotiation
.RE
.PP
\fB\-h, \-\-hostname {host}\fR
.RS 4
The fully\-qualified directory server host name that will be used when generating self\-signed certificates for LDAP SSL/StartTLS, the administration connector, and replication
.sp
Default value: localhost\&.localdomain
.RE
.PP
\fB\-i, \-\-cli\fR
.RS 4
Use the command line install\&. If not specified the graphical interface will be launched\&. The rest of the options (excluding help and version) will only be taken into account if this option is specified
.RE
.PP
\fB\-j, \-\-rootUserPasswordFile {rootUserPasswordFile}\fR
.RS 4
Path to a file containing the password for the initial root user for the directory server
.RE
.PP
\fB\-l, \-\-ldifFile {ldifFile}\fR
.RS 4
Path to an LDIF file containing data that should be added to the directory server database\&. Multiple LDIF files may be provided by using this option multiple times
.RE
.PP
\fB\-N, \-\-certNickname {nickname}\fR
.RS 4
Nickname of the certificate that the server should use when accepting SSL\-based connections or performing StartTLS negotiation
.RE
.PP
\fB\-O, \-\-doNotStart\fR
.RS 4
Do not start the server when the configuration is completed
.RE
.PP
\fB\-p, \-\-ldapPort {port}\fR
.RS 4
Port on which the Directory Server should listen for LDAP communication
.sp
Default value: 389
.RE
.PP
\fB\-q, \-\-enableStartTLS\fR
.RS 4
Enable StartTLS to allow secure communication with the server using the LDAP port
.RE
.PP
\fB\-R, \-\-rejectFile {rejectFile}\fR
.RS 4
Write rejected entries to the specified file
.RE
.PP
\fB\-S, \-\-skipPortCheck\fR
.RS 4
Skip the check to determine whether the specified ports are usable
.RE
.PP
\fB\-\-skipFile {skipFile}\fR
.RS 4
Write skipped entries to the specified file
.RE
.PP
\fB\-u, \-\-keyStorePasswordFile {keyStorePasswordFile}\fR
.RS 4
Certificate key store PIN file\&. A PIN is required when you specify to use an existing certificate (JKS, JCEKS, PKCS#12 or PKCS#11) as server certificate
.RE
.PP
\fB\-\-useJavaKeystore {keyStorePath}\fR
.RS 4
Path of a Java Key Store (JKS) containing a certificate to be used as the server certificate
.RE
.PP
\fB\-\-useJCEKS {keyStorePath}\fR
.RS 4
Path of a JCEKS containing a certificate to be used as the server certificate
.RE
.PP
\fB\-\-usePkcs11Keystore\fR
.RS 4
Use a certificate in a PKCS#11 token that the server should use when accepting SSL\-based connections or performing StartTLS negotiation
.RE
.PP
\fB\-\-usePkcs12keyStore {keyStorePath}\fR
.RS 4
Path of a PKCS#12 key store containing the certificate that the server should use when accepting SSL\-based connections or performing StartTLS negotiation
.RE
.PP
\fB\-w, \-\-rootUserPassword {rootUserPassword}\fR
.RS 4
Password for the initial root user for the Directory Server
.RE
.PP
\fB\-W, \-\-keyStorePassword {keyStorePassword}\fR
.RS 4
Certificate key store PIN\&. A PIN is required when you specify to use an existing certificate (JKS, JCEKS, PKCS#12 or PKCS#11) as server certificate
.RE
.PP
\fB\-x, \-\-jmxPort {jmxPort}\fR
.RS 4
Port on which the Directory Server should listen for JMX communication
.sp
Default value: 1689
.RE
.PP
\fB\-Z, \-\-ldapsPort {port}\fR
.RS 4
Port on which the Directory Server should listen for LDAPS communication\&. The LDAPS port will be configured and SSL will be enabled only if this argument is explicitly specified
.sp
Default value: 636
.RE
.SS "Utility Input/Output Options"
.PP
\fB\-n, \-\-no\-prompt\fR
.RS 4
Use non\-interactive mode\&. If data in the command is missing, the user is not prompted and the tool will fail
.RE
.PP
\fB\-\-noPropertiesFile\fR
.RS 4
No properties file will be used to get default command line argument values
.RE
.PP
\fB\-\-propertiesFilePath {propertiesFilePath}\fR
.RS 4
Path to the file containing default property values used for command line arguments
.RE
.PP
\fB\-Q, \-\-quiet\fR
.RS 4
Run setup in quiet mode\&. Quiet mode will not output progress information to standard output
.RE
.PP
\fB\-v, \-\-verbose\fR
.RS 4
Use verbose mode
.RE
.SS "General Options"
.PP
\fB\-V, \-\-version\fR
.RS 4
Display version information
.RE
.PP
\fB\-?, \-H, \-\-help\fR
.RS 4
Display usage information
.RE
.SH "EXIT CODES"
.PP
0
.RS 4
The command completed successfully\&.
.RE
.PP
> 0
.RS 4
An error occurred\&.
.RE
.SH "EXAMPLES"
.PP
The following command installs OpenDJ directory server, enabling StartTLS and importing 100 example entries without interaction\&.
.sp
.if n \{\
.RS 4
.\}
.nf
$ \&./opendj/setup \-\-cli \-b dc=example,dc=com \-d 100 \-D "cn=Directory Manager"
 \-w password \-h `hostname` \-p 1389
 \-\-generateSelfSignedCertificate \-\-enableStartTLS \-n 

OpenDJ 2\&.6\&.0
Please wait while the setup program initializes\&.\&.\&.

See /var/\&.\&.\&./opends\-setup\-484\&.\&.\&.561\&.log for a detailed log of this operation\&.

Configuring Directory Server \&.\&.\&.\&.\&. Done\&.
Configuring Certificates \&.\&.\&.\&.\&. Done\&.
Importing Automatically\-Generated Data (100 Entries) \&.\&.\&.\&.\&.\&.\&.\&.\&. Done\&.
Starting Directory Server \&.\&.\&.\&.\&.\&.\&.\&.\&.\&. Done\&.

To see basic server configuration status and configuration you can launch
 /path/to/opendj/bin/status
.fi
.if n \{\
.RE
.\}
.SH "COPYRIGHT"
.br
Copyright \(co 2011-2013 ForgeRock AS
.br
