'\" t
.\"     Title: uninstall
.\"    Author: 
.\" Generator: DocBook XSL-NS Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 05/16/2013
.\"    Manual: Tools Reference
.\"    Source: OpenDJ 2.6.0
.\"  Language: English
.\"
.TH "UNINSTALL" "1" "05/16/2013" "OpenDJ 2\&.6\&.0" "Tools Reference"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
uninstall \- remove OpenDJ directory server software
.SH "SYNOPSIS"
.HP \w'\fBuninstall\fR\ 'u
\fBuninstall\fR [options]
.SH "DESCRIPTION"
.PP
This utility can be used to uninstall the directory server\&.
.SH "OPTIONS"
.PP
The following options are supported\&.
.PP
\fB\-a, \-\-remove\-all\fR
.RS 4
Remove all components of the server (this option is not compatible with the rest of remove options)
.RE
.PP
\fB\-b, \-\-backup\-files\fR
.RS 4
Remove backup files
.RE
.PP
\fB\-c, \-\-configuration\-files\fR
.RS 4
Remove configuration files
.RE
.PP
\fB\-d, \-\-databases\fR
.RS 4
Remove database contents
.RE
.PP
\fB\-e, \-\-ldif\-files\fR
.RS 4
Remove LDIF files
.RE
.PP
\fB\-f, \-\-forceOnError\fR
.RS 4
Specifies whether the uninstall should continue if there is an error updating references to this server in remote server instances or not\&. This option can only be used with the \-\-no\-prompt option\&.
.RE
.PP
\fB\-i, \-\-cli\fR
.RS 4
Specifies to use the command line install\&. If not specified the graphical interface will be launched\&. The rest of the options (excluding help and version) will only be taken into account if this option is specified
.RE
.PP
\fB\-l, \-\-server\-libraries\fR
.RS 4
Remove Server Libraries and Administrative Tools
.RE
.PP
\fB\-L, \-\-log\-files\fR
.RS 4
Remove log files
.RE
.SS "LDAP Connection Options"
.PP
\fB\-\-connectTimeout {timeout}\fR
.RS 4
Maximum length of time (in milliseconds) that can be taken to establish a connection\&. Use \*(Aq0\*(Aq to specify no time out\&.
.sp
Default value: 30000
.RE
.PP
\fB\-h, \-\-referencedHostName {host}\fR
.RS 4
The name of this host (or IP address) as it is referenced in remote servers for replication
.sp
Default value: localhost\&.localdomain
.RE
.PP
\fB\-I, \-\-adminUID {adminUID}\fR
.RS 4
User ID of the Global Administrator to use to bind to the server\&.
.sp
Default value: admin
.RE
.PP
\fB\-j, \-\-bindPasswordFile {bindPasswordFile}\fR
.RS 4
Bind password file
.RE
.PP
\fB\-K, \-\-keyStorePath {keyStorePath}\fR
.RS 4
Certificate key store path
.RE
.PP
\fB\-N, \-\-certNickname {nickname}\fR
.RS 4
Nickname of certificate for SSL client authentication
.RE
.PP
\fB\-o, \-\-saslOption {name=value}\fR
.RS 4
SASL bind options
.RE
.PP
\fB\-P, \-\-trustStorePath {trustStorePath}\fR
.RS 4
Certificate trust store path
.RE
.PP
\fB\-T, \-\-trustStorePassword {trustStorePassword}\fR
.RS 4
Certificate trust store PIN
.RE
.PP
\fB\-u, \-\-keyStorePasswordFile {keyStorePasswordFile}\fR
.RS 4
Certificate key store PIN file
.RE
.PP
\fB\-U, \-\-trustStorePasswordFile {path}\fR
.RS 4
Certificate trust store PIN file
.RE
.PP
\fB\-w, \-\-bindPassword {bindPassword}\fR
.RS 4
Password to use to bind to the server
.RE
.PP
\fB\-W, \-\-keyStorePassword {keyStorePassword}\fR
.RS 4
Certificate key store PIN
.RE
.PP
\fB\-X, \-\-trustAll\fR
.RS 4
Trust all server SSL certificates
.RE
.SS "Utility Input/Output Options"
.PP
\fB\-n, \-\-no\-prompt\fR
.RS 4
Use non\-interactive mode\&. If data in the command is missing, the user is not prompted and the tool will fail
.RE
.PP
\fB\-\-noPropertiesFile\fR
.RS 4
No properties file will be used to get default command line argument values
.RE
.PP
\fB\-\-propertiesFilePath {propertiesFilePath}\fR
.RS 4
Path to the file containing default property values used for command line arguments
.RE
.PP
\fB\-Q, \-\-quiet\fR
.RS 4
Run setup in quiet mode\&. Quiet mode will not output progress information to standard output
.RE
.PP
\fB\-v, \-\-verbose\fR
.RS 4
Use verbose mode
.RE
.SS "General Options"
.PP
\fB\-V, \-\-version\fR
.RS 4
Display version information
.RE
.PP
\fB\-?, \-H, \-\-help\fR
.RS 4
Display usage information
.RE
.SH "EXIT CODES"
.PP
0
.RS 4
The command completed successfully\&.
.RE
.PP
> 0
.RS 4
An error occurred\&.
.RE
.SH "EXAMPLES"
.PP
The following command removes OpenDJ directory server without interaction\&.
.sp
.if n \{\
.RS 4
.\}
.nf
$ \&./opendj/uninstall \-a \-\-cli \-I admin \-w password \-n

Stopping Directory Server \&.\&.\&.\&.\&. Done\&.
Deleting Files under the Installation Path \&.\&.\&.\&.\&. Done\&.

The Uninstall Completed Successfully\&.
To complete the uninstallation, you must delete manually the following files
and directories:
/path/to/opendj/lib
See /var/\&.\&.\&./opends\-uninstall\-3\&.\&.\&.0\&.log for a detailed log of this operation\&.
$ rm \-rf opendj
.fi
.if n \{\
.RE
.\}
.SH "COPYRIGHT"
.br
Copyright \(co 2011-2013 ForgeRock AS
.br
