'\" t
.\"     Title: verify-index
.\"    Author: 
.\" Generator: DocBook XSL-NS Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 03/21/2012
.\"    Manual: Tools Reference
.\"    Source: OpenDJ 2.5.0
.\"  Language: English
.\"
.TH "VERIFY\-INDEX" "1" "03/21/2012" "OpenDJ 2\&.5\&.0" "Tools Reference"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
verify-index \- check index for consistency or errors
.SH "SYNOPSIS"
.HP \w'\fBverify\-index\fR\ 'u
\fBverify\-index\fR {options}
.SH "DESCRIPTION"
.PP
This utility can be used to ensure that index data is consistent within a backend based on the Berkeley DB Java Edition\&.
.SH "OPTIONS"
.PP
The following options are supported\&.
.PP
\fB\-b, \-\-baseDN {baseDN}\fR
.RS 4
Base DN of a backend supporting indexing\&. Verification is performed on indexes within the scope of the given base DN\&.
.RE
.PP
\fB\-c, \-\-clean\fR
.RS 4
Specifies that a single index should be verified to ensure it is clean\&. An index is clean if each index value references only entries containing that value\&. Only one index at a time may be verified in this way\&.
.RE
.PP
\fB\-\-countErrors\fR
.RS 4
Count the number of errors found during the verification and return that value as the exit code (values > 255 will be reduced to 255 due to exit code restrictions)\&.
.RE
.PP
\fB\-i, \-\-index {index}\fR
.RS 4
Name of an index to be verified\&. For an attribute index this is simply an attribute name\&. Multiple indexes may be verified for completeness, or all indexes if no indexes are specified\&. An index is complete if each index value references all entries containing that value\&.
.RE
.SS "General Options"
.PP
\fB\-V, \-\-version\fR
.RS 4
Display version information
.RE
.PP
\fB\-?, \-H, \-\-help\fR
.RS 4
Display usage information
.RE
.SH "EXIT CODES"
.PP
0
.RS 4
The command completed successfully\&.
.RE
.PP
1
.RS 4
An error occurred while parsing the command\-line arguments\&.
.RE
.PP
0\-255
.RS 4
The number of errors in the index, as indicated for the
\fB\-\-countErrors\fR
option\&.
.RE
.SH "EXAMPLES"
.PP
The following example verifies the
cn
(common name) index for completeness and for errors\&.
.sp
.if n \{\
.RS 4
.\}
.nf
$ verify\-index \-b dc=example,dc=com \-i cn \-\-clean \-\-countErrors
[07/Jun/2011:16:06:50 +0200] category=BACKEND severity=INFORMATION
 msgID=9437595 msg=Local DB backend userRoot does not specify the number of
 lock tables: defaulting to 97
[07/Jun/2011:16:06:50 +0200] category=BACKEND severity=INFORMATION
 msgID=9437594 msg=Local DB backend userRoot does not specify the number of
 cleaner threads: defaulting to 24 threads
[07/Jun/2011:16:06:51 +0200] category=JEB severity=NOTICE msgID=8847461
 msg=Checked 1316 records and found 0 error(s) in 0 seconds
 (average rate 2506\&.7/sec)
[07/Jun/2011:16:06:51 +0200] category=JEB severity=INFORMATION
 msgID=8388710 msg=Number of records referencing more than one entry: 315
[07/Jun/2011:16:06:51 +0200] category=JEB severity=INFORMATION
 msgID=8388711 msg=Number of records that exceed the entry limit: 0
[07/Jun/2011:16:06:51 +0200] category=JEB severity=INFORMATION
 msgID=8388712 msg=Average number of entries referenced is 1\&.58/record
[07/Jun/2011:16:06:51 +0200] category=JEB severity=INFORMATION
 msgID=8388713 msg=Maximum number of entries referenced by any
 record is 32
.fi
.if n \{\
.RE
.\}
.SH "COPYRIGHT"
.br
Copyright \(co 2011-2012 ForgeRock AS
.br
