#!/bin/bash
#
# The contents of this file are subject to the terms of the Common Development and
# Distribution License (the License). You may not use this file except in compliance with the
# License.
#
# You can obtain a copy of the License at legal/CDDLv1.0.txt. See the License for the
# specific language governing permission and limitations under the License.
#
# When distributing Covered Software, include this CDDL Header Notice in each file and include
# the License file at legal/CDDLv1.0.txt. If applicable, add the following below the CDDL
# Header, with the fields enclosed by brackets [] replaced by your own identifying
# information: "Portions Copyright [year] [name of copyright owner]".
#
# Copyright 2013-2015 ForgeRock AS.
# Portions Copyright 2026 3A Systems, LLC

set -e

# Pre installation script.
if [ "$1" = "upgrade" ] ; then
    # Only act if the instance has been configured.
    if [ -f ${deb.prefix}/config/buildinfo ] && [ "$(ls -A ${deb.prefix}/config/archived-configs 2>/dev/null)" ] ; then
        # If the server is running before the upgrade, record it so postinst can restart it.
        if [ -f ${deb.prefix}/logs/server.pid ] ; then
            touch ${deb.prefix}/logs/status
        fi
        echo "*Stopping OpenDJ server..."
        if [ -d /run/systemd/system ] ; then
            deb-systemd-invoke stop opendj.service || true
        fi
        [ -x ${deb.prefix}/bin/stop-ds ] && ${deb.prefix}/bin/stop-ds || true
    fi
fi
echo
# End of the pre installation script
