#!/bin/bash
#
# The contents of this file are subject to the terms of the Common Development and
# Distribution License (the License). You may not use this file except in compliance with the
# License.
#
# You can obtain a copy of the License at legal/CDDLv1.0.txt. See the License for the
# specific language governing permission and limitations under the License.
#
# When distributing Covered Software, include this CDDL Header Notice in each file and include
# the License file at legal/CDDLv1.0.txt. If applicable, add the following below the CDDL
# Header, with the fields enclosed by brackets [] replaced by your own identifying
# information: "Portions Copyright [year] [name of copyright owner]".
#
# Copyright 2013-2015 ForgeRock AS.

set -e

# Pre installation script
if [ "$1" = "upgrade" ] ; then
    # Only if the instance has been configured
    if [ -f ${deb.prefix}/config/buildinfo ] && [ "$(ls -A ${deb.prefix}/config/archived-configs)" ] ; then
        # If the server is running before upgrade, creates a flag.
        if [ -f ${deb.prefix}/logs/server.pid ] ; then
            touch ${deb.prefix}/logs/status
        fi
        echo *Stopping OpenDJ server...
        ${deb.prefix}/bin/./stop-ds
    else
        echo "Instance is not configured. Upgrade aborted."
        exit -1
    fi
fi
echo
# End of the pre installation script
