#!/bin/bash
#
# The contents of this file are subject to the terms of the Common Development and
# Distribution License (the License). You may not use this file except in compliance with the
# License.
#
# You can obtain a copy of the License at legal/CDDLv1.0.txt. See the License for the
# specific language governing permission and limitations under the License.
#
# When distributing Covered Software, include this CDDL Header Notice in each file and include
# the License file at legal/CDDLv1.0.txt. If applicable, add the following below the CDDL
# Header, with the fields enclosed by brackets [] replaced by your own identifying
# information: "Portions Copyright [year] [name of copyright owner]".
#
# Copyright 2013-2015 ForgeRock AS.
# Portions Copyright 2026 3A Systems, LLC

set -e
# Pre rm script.

# Stop the service before the package files are removed.
if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ] ; then
    if [ -d /run/systemd/system ] ; then
        deb-systemd-invoke stop opendj.service || true
    fi
    if [ -x ${deb.prefix}/bin/stop-ds ] && [ -f ${deb.prefix}/config/buildinfo ] \
       && [ "$(ls -A ${deb.prefix}/config/archived-configs 2>/dev/null)" ] ; then
        ${deb.prefix}/bin/stop-ds || true
    fi
fi

# Clean up the legacy PID symlink created by the SysV init script.
[ -h /run/opendj.pid ] && rm -f /run/opendj.pid || true
[ -h /var/run/opendj.pid ] && rm -f /var/run/opendj.pid || true

exit 0
# End prerm script
