#!/bin/bash
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License, Version 1.0 only
# (the "License").  You may not use this file except in compliance
# with the License.
#
# You can obtain a copy of the license at legal-notices/CDDLv1_0.txt
# or http://forgerock.org/license/CDDLv1.0.html.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at
# legal-notices/CDDLv1_0.txt.  If applicable,
# add the following below this CDDL HEADER, with the fields enclosed
# by brackets "[]" replaced with your own identifying information:
#      Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#      Copyright 2013-2015 ForgeRock AS.
#

set -e
# Post install script
# Install is launched with an empty second arg.
# If the package is already installed, the second arg. is not empty.

# Registers the service
update-rc.d opendj defaults

# Symlinks to process ID
test -h "/var/run/opendj.pid" || ln -s ${deb.prefix}/logs/server.pid /var/run/opendj.pid

# In this case, we are in upgrade mode.
if [ "$1" = "configure" ] && [ ! -z "$2" ] ; then
    # For being secure, we check the buildinfo file too.
    if [ -f ${deb.prefix}/config/buildinfo ] ; then
        echo *Starting upgrade...
        ${deb.prefix}/./upgrade -n --acceptLicense
        echo
        if [ "$?" -eq 2 ] ; then
            # Upgrade fails - Requires mandatory user interaction.
            # Nevertheless, exits successfully of the pkg process.
            exit 0
        fi

        if [ "$?" -eq 0 ] ; then
            # Restarts the service if needed.
            # If server is stopped by upgrade process, the server will restart after upgrade.
            # If server is stopped before the upgrade process (eg. upgrade the new package), the server will not restart.
            # Uses the flag for determining server status at this point.
            if [ -f ${deb.prefix}/logs/status ] ; then
                echo
                echo "*Restarting server..."
                ${deb.prefix}/./bin/start-ds
                rm -f ${deb.prefix}/logs/status
            fi
        fi
    else
        echo "Invalid installation, could not find the build info file."
        exit -1
    fi
fi
# End post install script
echo
