#!/bin/bash
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License, Version 1.0 only
# (the "License").  You may not use this file except in compliance
# with the License.
#
# You can obtain a copy of the license at legal-notices/CDDLv1_0.txt
# or http://forgerock.org/license/CDDLv1.0.html.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at
# legal-notices/CDDLv1_0.txt.  If applicable,
# add the following below this CDDL HEADER, with the fields enclosed
# by brackets "[]" replaced with your own identifying information:
#      Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#      Copyright 2013-2015 ForgeRock AS.
#

set -e

# Pre installation script
if [ "$1" = "upgrade" ] ; then
    # Only if the instance has been configured
    if [ -f ${deb.prefix}/config/buildinfo ] && [ "$(ls -A ${deb.prefix}/config/archived-configs)" ] ; then
        # If the server is running before upgrade, creates a flag.
        if [ -f ${deb.prefix}/logs/server.pid ] ; then
            touch ${deb.prefix}/logs/status
        fi
        echo *Stopping OpenDJ server...
        ${deb.prefix}/bin/./stop-ds
    else
        echo "Instance is not configured. Upgrade aborded."
        exit -1
    fi
fi
echo
# End of the pre installation script
