////

  The contents of this file are subject to the terms of the Common Development and
  Distribution License (the License). You may not use this file except in compliance with the
  License.

  You can obtain a copy of the License at legal/CDDLv1.0.txt. See the License for the
  specific language governing permission and limitations under the License.

  When distributing Covered Software, include this CDDL Header Notice in each file and include
  the License file at legal/CDDLv1.0.txt. If applicable, add the following below the CDDL
  Header, with the fields enclosed by brackets [] replaced by your own identifying
  information: "Portions Copyright [year] [name of copyright owner]".

  Copyright 2015 ForgeRock AS.
  Portions Copyright 2024 3A Systems LLC.

////

== Attributes
The optional attribute list specifies the attributes to return in the entries found
by the search. In addition to identifying attributes by name such as `cn sn mail`
and so forth, you can use the following notations, too.
--

`*`::
Return all user attributes such as `cn`, `sn`, and `mail`.

`+`::
Return all operational attributes such as `etag` and `pwdPolicySubentry`.

`@objectclass`::
Return all attributes of the specified object class, where __objectclass__ is one of the object classes on the entries returned by the search.

`1.1`::
Return no attributes, only the DNs of matching entries.

--

