////

  The contents of this file are subject to the terms of the Common Development and
  Distribution License (the License). You may not use this file except in compliance with the
  License.

  You can obtain a copy of the License at legal/CDDLv1.0.txt. See the License for the
  specific language governing permission and limitations under the License.

  When distributing Covered Software, include this CDDL Header Notice in each file and include
  the License file at legal/CDDLv1.0.txt. If applicable, add the following below the CDDL
  Header, with the fields enclosed by brackets [] replaced by your own identifying
  information: "Portions Copyright [year] [name of copyright owner]".

  Copyright 2015 ForgeRock AS.
  Portions Copyright 2024-2026 3A Systems LLC.

////

== Files
You can use `~/.opendj/tools.properties` to set the defaults for bind DN, host name,
and port number as in the following example.

[source, ini]
----
hostname=directory.example.com
port=1389
bindDN=uid=kvaughan,ou=People,dc=example,dc=com

ldapcompare.port=1389
ldapdelete.port=1389
ldapmodify.port=1389
ldappasswordmodify.port=1389
ldapsearch.port=1389
----

The location on Windows is `%UserProfile%/.opendj/tools.properties`.

The file is read as UTF-8, or as ISO-8859-1 if it is not valid UTF-8. It uses the Java properties format, where a backslash starts an escape sequence. Double each backslash in a value, for example `bindDN=cn=a\\,b,dc=example,dc=com` for the DN `cn=a\,b,dc=example,dc=com`.
