////

  The contents of this file are subject to the terms of the Common Development and
  Distribution License (the License). You may not use this file except in compliance with the
  License.

  You can obtain a copy of the License at legal/CDDLv1.0.txt. See the License for the
  specific language governing permission and limitations under the License.

  When distributing Covered Software, include this CDDL Header Notice in each file and include
  the License file at legal/CDDLv1.0.txt. If applicable, add the following below the CDDL
  Header, with the fields enclosed by brackets [] replaced by your own identifying
  information: "Portions Copyright [year] [name of copyright owner]".

  Copyright 2015-2016 ForgeRock AS.
  Portions Copyright 2024 3A Systems LLC.

////

[open]
====
For some __controloid__ values, you can replace object identifiers with user-friendly strings. The strings are listed here in lower case, but the case is not important. You can use camelCase if you prefer, for example.

`accountusable`,`accountusability`::
Account Usability Control, Object Identifier: 1.3.6.1.4.1.42.2.27.9.5.8

`authzid`,`authorizationidentity`::
Authorization Identity Request Control, Object Identifier: 2.16.840.1.113730.3.4.16

`effectiverights`,`geteffectiverights`::
Get Effective Rights Request Control, Object Identifier: 1.3.6.1.4.1.42.2.27.9.5.2

`managedsait`::
Manage DSAIT Request Control, Object Identifier: 2.16.840.1.113730.3.4.2

`noop`,`no-op`::
No-Op Control, Object Identifier: 1.3.6.1.4.1.4203.1.10.2

`pwpolicy`,`passwordpolicy`::
Password Policy Control, Object Identifier: 1.3.6.1.4.1.42.2.27.8.5.1

`realattrsonly`,`realattributesonly`::
Real Attributes Only Request Control, Object Identifier: 2.16.840.1.113730.3.4.17

`subtreedelete`,`treedelete`::
Subtree Delete Request Control, Object Identifier: 1.2.840.113556.1.4.805

`virtualattrsonly`,`virtualattributesonly`::
Virtual Attributes Only Request Control, Object Identifier: 2.16.840.1.113730.3.4.19

====
