#!/bin/sh

cygwin=false;
case "`uname`" in
  CYGWIN*) cygwin=true ;;
esac

SVNKIT_HOME=`dirname $0`
SVNKIT_HOME=`cd "$SVNKIT_HOME" ; pwd`

SVNKIT_CP=$SVNKIT_HOME/svnkit.jar:$SVNKIT_HOME/svnkit-cli.jar:$SVNKIT_HOME/ganymed.jar

if $cygwin ; then
  SVNKIT_CP=`cygpath --windows --path "$SVNKIT_CP"`
  [ -n "$SVNKIT_LOGDIR" ] &&
    SVNKIT_LOGDIR=`cygpath --unix "$SVNKIT_LOGDIR"`
fi

if [ ! -d $SVNKIT_LOGDIR ]; then
	mkdir $SVNKIT_LOGDIR
fi

SVNKIT_VM_OPTIONS="-Dsun.io.useCanonCaches=false -Djava.util.logging.config.file=$SVNKIT_HOME/logging.properties"

SVNKIT_MAINCLASS=org.tmatesoft.svn.cli.SVNSync
$JAVA_HOME/bin/java $SVNKIT_VM_OPTIONS -cp $SVNKIT_CP $SVNKIT_MAINCLASS "$@"
