#!/bin/sh
set -e
# PRERM - Upgrade or remove script
if [ $1 = "upgrade" -o $1 = "remove" ] ; then
  echo *Stopping OpenDJ server...
  @prefix@/bin/stop-ds
fi
echo 
# End prem - upgrade or remove script