echo "Backing configuration up"
me "${tests.config}" "${tests.config.backup}"
echo "Loading configuration as of ${tests.run.time}"
cp "${tests.run.dir}${file.separator}${tests.run.time}${file.separator}config${file.separator}${tests.config.file}" "${tests.config}"
echo "Starting test run"
"${staf.install.dir}${file.separator}bin${file.separator}STAF" local STAX "${tests.request}"
echo "Removing configuration of ${tests.run.time}"
rm -f "${tests.config}"
echo "Restoring original configuration"
mv "${tests.config.backup}" "${tests.config}"
