#!/bin/bash
set -e
# Pre installation script
# If the server is running before upgrade, creates a flag.
if [ "$1" = "upgrade" ]
then
  if [ -f @prefix@/logs/server.pid ]
  then
    touch @prefix@/logs/status
  fi
  echo *Stopping OpenDJ server...
  @prefix@/bin/./stop-ds
fi
echo 
# End of the pre installation script