#!/bin/bash
set -e
# Pre rm script
# Stops the server
# Only if the instance has been configured
if [ "$1" = "remove" ] && ( [ -f @prefix@/config/buildinfo ] && [ "$(ls -A @prefix@/config/archived-configs)" ] )
then
  echo *Stopping OpenDJ server...
  @prefix@/bin/./stop-ds
fi
# End prem script