////
  The contents of this file are subject to the terms of the Common Development and
  Distribution License (the License). You may not use this file except in compliance with the
  License.
 
  You can obtain a copy of the License at legal/CDDLv1.0.txt. See the License for the
  specific language governing permission and limitations under the License.
 
  When distributing Covered Software, include this CDDL Header Notice in each file and include
  the License file at legal/CDDLv1.0.txt. If applicable, add the following below the CDDL
  Header, with the fields enclosed by brackets [] replaced by your own identifying
  information: "Portions copyright [year] [name of copyright owner]".
 
  Copyright 2017 ForgeRock AS.
  Portions Copyright 2024 3A Systems LLC.
////

:figure-caption!:
:example-caption!:
:table-caption!:


[appendix]
[#appendix-extended-ops]
== LDAP Extended Operations

Extended operations allow additional operations to be defined for services not already available in the protocol

OpenDJ software supports the following LDAP extended operations:
--

[#cancel-extended-request]
Cancel Extended Request::
+
Object Identifier: 1.3.6.1.1.8

+
RFC: link:http://tools.ietf.org/html/rfc3909[RFC 3909 - Lightweight Directory Access Protocol (LDAP) Cancel Operation, window=\_top]

[#get-connection-id-extended-request]
Get Connection ID Extended Request::
+
Object Identifier: 1.3.6.1.4.1.26027.1.6.2

+
OpenDJ extended operation to return the connection ID of the associated client connection. This extended operation is intended for OpenDJ internal use.

[#password-modify-extended-request]
Password Modify Extended Request::
+
Object Identifier: 1.3.6.1.4.1.4203.1.11.1

+
RFC: link:http://tools.ietf.org/html/rfc3062[RFC 3062 - LDAP Password Modify Extended Operation, window=\_top]

[#password-policy-state-extended-operation]
Password Policy State Extended Operation::
+
Object Identifier: 1.3.6.1.4.1.26027.1.6.1

+
OpenDJ extended operation to query and update password policy state for a given user entry. This extended operation is intended for OpenDJ internal use.

[#start-transport-layer-security-extended-request]
Start Transport Layer Security Extended Request::
+
Object Identifier: 1.3.6.1.4.1.1466.20037

+
RFC: link:http://tools.ietf.org/html/rfc4511[RFC 4511 - Lightweight Directory Access Protocol (LDAP): The Protocol, window=\_top]

[#who-am-i-extended-request]
Who am I? Extended Request::
+
Object Identifier: 1.3.6.1.4.1.4203.1.11.3

+
RFC: link:http://tools.ietf.org/html/rfc4532[RFC 4532 - Lightweight Directory Access Protocol (LDAP) "Who am I?" Operation, window=\_top]

--

