'\" t
.\"     Title: encode-password
.\"    Author: 
.\" Generator: DocBook XSL-NS Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 03/21/2012
.\"    Manual: Tools Reference
.\"    Source: OpenDJ 2.5.0
.\"  Language: English
.\"
.TH "ENCODE\-PASSWORD" "1" "03/21/2012" "OpenDJ 2\&.5\&.0" "Tools Reference"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
encode-password \- encode a password with an OpenDJ storage scheme
.SH "SYNOPSIS"
.HP \w'\fBencode\-password\fR\ 'u
\fBencode\-password\fR {options}
.SH "DESCRIPTION"
.PP
This utility can be used to encode user passwords with a specified storage scheme, or to determine whether a given clear\-text value matches a provided encoded password\&.
.SH "OPTIONS"
.PP
The following global options are supported\&.
.PP
\fB\-a, \-\-authPasswordSyntax\fR
.RS 4
Use the authentication password syntax rather than the user password syntax\&.
.RE
.PP
\fB\-c, \-\-clearPassword {clearPW}\fR
.RS 4
Clear\-text password to encode or to compare against an encoded password\&.
.RE
.PP
\fB\-e, \-\-encodedPassword {encodedPW}\fR
.RS 4
Encoded password to compare against the clear\-text password\&.
.RE
.PP
\fB\-E, \-\-encodedPasswordFile {file}\fR
.RS 4
Encoded password file\&.
.RE
.PP
\fB\-f, \-\-clearPasswordFile {file}\fR
.RS 4
Clear\-text password file\&.
.RE
.PP
\fB\-i, \-\-interactivePassword\fR
.RS 4
The password to encode or to compare against an encoded password is interactively asked to the user\&.
.RE
.PP
\fB\-l, \-\-listSchemes\fR
.RS 4
List available password storage schemes\&.
.RE
.PP
\fB\-r, \-\-useCompareResultCode\fR
.RS 4
Use the LDAP compare result as an exit code for the password comparison\&.
.RE
.PP
\fB\-s, \-\-storageScheme {scheme}\fR
.RS 4
Scheme to use for the encoded password\&.
.RE
.PP
\fB\-V, \-\-version\fR
.RS 4
Display version information\&.
.RE
.PP
\fB\-?, \-H, \-\-help\fR
.RS 4
Display usage information\&.
.RE
.SH "EXIT CODES"
.PP
0
.RS 4
The command completed successfully\&.
.RE
.PP
5
.RS 4
The
\fB\-r\fR
option was used, and the compare did not match\&.
.RE
.PP
6
.RS 4
The
\fB\-r\fR
option was used, and the compare did match\&.
.RE
.PP
other
.RS 4
An error occurred\&.
.RE
.SH "EXAMPLES"
.PP
The following example encodes a password, and also shows comparison of a password with the encoded value\&.
.sp
.if n \{\
.RS 4
.\}
.nf
$ encode\-password \-l
3DES
AES
BASE64
BLOWFISH
CLEAR
CRYPT
MD5
RC4
SHA
SMD5
SSHA
SSHA256
SSHA384
SSHA512
$ encode\-password \-c secret12 \-s CRYPT
Encoded Password:  "{CRYPT}ZulJ6Dy3TFnrE"
$ encode\-password \-c secret12 \-s CRYPT \-e "{CRYPT}ZulJ6Dy3TFnrE" \-r
The provided clear\-text and encoded passwords match
$ echo $?
6
.fi
.if n \{\
.RE
.\}
.SH "COPYRIGHT"
.br
Copyright \(co 2011-2012 ForgeRock AS
.br
