#!/bin/sh
#
# The contents of this file are subject to the terms of the Common Development and
# Distribution License (the License). You may not use this file except in compliance with the
# License.
#
# You can obtain a copy of the License at legal/CDDLv1.0.txt. See the License for the
# specific language governing permission and limitations under the License.
#
# When distributing Covered Software, include this CDDL Header Notice in each file and include
# the License file at legal/CDDLv1.0.txt. If applicable, add the following below the CDDL
# Header, with the fields enclosed by brackets [] replaced by your own identifying
# information: "Portions Copyright [year] [name of copyright owner]".
#
# Copyright 2013-2015 ForgeRock AS.


# This script may be used to perform a backup of a Directory Server backend.
OPENDJ_INVOKE_CLASS="org.opends.server.tools.upgrade.UpgradeCli"
export OPENDJ_INVOKE_CLASS

SCRIPT_NAME="upgrade"
export SCRIPT_NAME

SCRIPT_DIR=`dirname "${0}"`

INSTALL_ROOT=${SCRIPT_DIR}
export INSTALL_ROOT

# Set environment variables
SCRIPT_UTIL_CMD=set-environment-vars
export SCRIPT_UTIL_CMD
.  "${INSTALL_ROOT}/lib/_script-util.sh"
RETURN_CODE=$?
if test ${RETURN_CODE} -ne 0
then
  exit ${RETURN_CODE}
fi

DIR_CLASSES="${INSTANCE_ROOT}/classes"
# The upgrade is not compatible with patches. If the folder is not empty
# we renamed it as "classes.disabled", and the upgrade process should be launched properly.
if [ "`(ls -A ${DIR_CLASSES})`" ]; then
    mv -f ${DIR_CLASSES} "${INSTANCE_ROOT}/classes.disabled"
    mkdir ${DIR_CLASSES}
fi

"${SCRIPT_DIR}/lib/_server-script.sh" "${@}"
